pipeline {
	agent any
	stages {
		stage ('HolaMundo') {
			steps {
				echo "ID_USUARIO: 1 Nombre usuario: Vergara, Enrique Fecha: 2022-09-12"
				echo "- Capital: A Coruña, Provincia: A Coruña"
				echo "- Capital: Alacant, Provincia: Alacant"
				echo "- Capital: Albacete, Provincia: Albacete"
				echo "- Capital: Almería, Provincia: Almería"
				echo "- Capital: Araba, Provincia: Araba"
				echo "- Capital: Asturias, Provincia: Asturias"
				echo "- Capital: Badajoz, Provincia: Badajoz"
				echo "- Capital: Barcelona, Provincia: Barcelona"
				echo "- Capital: Bizkaia, Provincia: Bizkaia"
				echo "- Capital: Burgos, Provincia: Burgos"
				echo "- Capital: Cantabria, Provincia: Cantabria"
				echo "- Capital: Castelló, Provincia: Castelló"
				echo "- Capital: Ceuta, Provincia: Ceuta"
				echo "- Capital: Ciudad Real, Provincia: Ciudad Real"
				echo "- Capital: Cuenca, Provincia: Cuenca"
				echo "- Capital: Cáceres, Provincia: Cáceres"
				echo "- Capital: Cádiz, Provincia: Cádiz"
				echo "- Capital: Córdoba, Provincia: Córdoba"
				echo "- Capital: Gipuzcoa, Provincia: Gipuzcoa"
				echo "- Capital: Girona, Provincia: Girona"
				echo "- Capital: Granada, Provincia: Granada"
				echo "- Capital: Guadalajara, Provincia: Guadalajara"
				echo "- Capital: Huelva, Provincia: Huelva"
				echo "- Capital: Huesca, Provincia: Huesca"
				echo "- Capital: Illes Balears, Provincia: Illes Balears"
				echo "- Capital: Jaén, Provincia: Jaén"
				echo "- Capital: La Rioja, Provincia: La Rioja"
				echo "- Capital: Las Palmas, Provincia: Las Palmas"
				echo "- Capital: León, Provincia: León"
				echo "- Capital: Lleida, Provincia: Lleida"
				echo "- Capital: Lugo, Provincia: Lugo"
				echo "- Capital: Madrid, Provincia: Madrid"
				echo "- Capital: Melilla, Provincia: Melilla"
				echo "- Capital: Murcia, Provincia: Murcia"
				echo "- Capital: Málaga, Provincia: Málaga"
				echo "- Capital: Navarra, Provincia: Navarra"
				echo "- Capital: Ourense, Provincia: Ourense"
				echo "- Capital: Palencia, Provincia: Palencia"
				echo "- Capital: Pontevedra, Provincia: Pontevedra"
				echo "- Capital: Salamanca, Provincia: Salamanca"
				echo "- Capital: Santa Cruz de Tenerife, Provincia: Santa Cruz de Tenerife"
				echo "- Capital: Segovia, Provincia: Segovia"
				echo "- Capital: Sevilla, Provincia: Sevilla"
				echo "- Capital: Soria, Provincia: Soria"
				echo "- Capital: Tarragona, Provincia: Tarragona"
				echo "- Capital: Teruel, Provincia: Teruel"
				echo "- Capital: Toledo, Provincia: Toledo"
				echo "- Capital: Valladolid, Provincia: Valladolid"
				echo "- Capital: València, Provincia: València"
				echo "- Capital: Zamora, Provincia: Zamora"
				echo "- Capital: Zaragoza, Provincia: Zaragoza"
				echo "- Capital: Ávila, Provincia: Ávila"
			}
		}
	}
}
